src/buy_it/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('account/', include('account.urls')),
    path('admin/', admin.site.urls),
    path('cart/', include('cart.urls', namespace='cart')),
    path('', include('shop.urls', namespace='shop')),
    path('orders/', include('orders.urls', namespace='orders')),
    path('flutterwave/', include('payments.urls', namespace='payments')),
    
    # python's social authentication module url
    path('social-auth/', include('social_django.urls', namespace='social')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                        document_root=settings.MEDIA_ROOT)

src/cart/urls.py
from django.urls import path
from .import views

app_name='cart'

urlpatterns = [
    path('', views.cart_detail, name='cart_detail'),
    path('add/<int:product_id>/', views.cart_add_product, name='add_product'),
    path('remove/<int:product_id>/', views.cart_remove_product, name='remove_product')
]

src/payments/urls.py
from django.urls import path
from . import views

app_name = 'payments'

urlpatterns = [
    #path('payment/', views.PaymentPageView.as_view(), name='payment'),
    path('payment/<int:id>/', views.paymentpage, name='payment'),
    path('paymentsuccess.html', views.paymentsuccess, name='success'),
    path('paymentfailure.html', views.paymentfailure, name='failure'),
]

src/payments/models.py
from django.db import models

# Create your models here.

src/payments/views.py
from django.shortcuts import render, get_object_or_404
from django.views.generic.base import  TemplateView
from django.conf import settings
from django.contrib.auth.decorators import login_required


from orders.models import Order

# Create your views here.

@login_required
class PaymentPageView(TemplateView):
    template_name = 'paymentpage.html'
    
    
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['key'] = settings.RAVE_PUBLIC_KEY
        order = get_object_or_404(Order, id=1)
        context['totalPrice'] = order.get_total_cost
        context['emailAddress'] = order.email
        return context


@login_required
def paymentpage(request, id):
    key = settings.RAVE_PUBLIC_KEY
    order = get_object_or_404(Order, id=id)
    totalPrice = order.get_total_cost()
    emailAddress = order.email
    telephone = order.telephone
    return render(request, 'paymentpage.html', {'key': key, 'totalPrice': totalPrice, 'emailAddress': emailAddress, 'telephone': telephone})


@login_required
def paymentsuccess(request):
    return render(request, "paymentsuccess.html")


@login_required
def paymentfailure(request):
    return render(request, 'paymentfailure.html')

src/payments/templates/paymentfailure.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Payment Not Successful</title>
</head>
<body>
    <h3>Payment was not successful</h3>
</body>
</html>

src/payments/templates/paymentpage.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <form>
        <script src="https://api.ravepay.co/flwv3-pug/getpaidx/api/flwpbf-inline.js"></script>
            <h3>Pay for the items you ordered here</h3>
            <button type="button" onClick="payWithRave()">Pay</button>
        </form>
        <script>
            const publicKey = "{{ key }}";
            var email_address = "{{ emailAddress }}";
            const totalPrice = "{{ totalPrice }}";
            const telephone = "{{telephone}}"
    
            function payWithRave() {
                var x = getpaidSetup({
                    PBFPubKey: publicKey,
                    //customer_email: "user@example.com",
                    //amount: 1,
                    customer_email: email_address,
                    customer_phone: telephone,
                    amount: totalPrice,
                    currency: "NGN",
                    txref: "rave-123456",
                    custom_title: "Wildlife Park",
                    onclose: function() {},
                    callback: function(response) {
                        var txref = response.tx.txRef;
                        console.log("This is the response returned after a charge", response);
                        if (
                            response.tx.chargeResponseCode == "00" ||
                            response.tx.chargeResponseCode == "0"
                        ) {
                            document.location.href = " {% url 'payments:success' %} "
                                // redirect to a success page
                        } else {
                            document.location.href = " {% url 'payments:failure' %} "
                            // redirect to a failure page.
                        }
                        x.close();
                    }
                });
            }
        </script>
</body>
</html>

src/payments/templates/paymentsuccess.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Payment Successful</title>
</head>
<body>
    <h3>Payment was successful</h3>
</body>
</html>